addons:
   apt:
       packages:
           - cmake
           - libgl1-mesa-dev
           - libxrandr-dev
           - libxinerama-dev
           - libxcursor-dev
sudo: required
dist: trusty

language: cpp
compiler:
           - clang
           - gcc

script: cmake . && make
